### ISSUE TITLE
Google Geocoder doesn't respond for db:seed

### ISSUE THREAD

**Issue by bryszard** [AgileVentures/LocalSupport#295]
There is a problem which is variable and sometimes shows itself to the full extent, sometimes not.

Shortly - often when rake db:seed is running, Google Geocoder shows this message:
![problem with google](https://cloud.githubusercontent.com/assets/12682792/14812667/6a075480-0b9e-11e6-83d7-087a13e6afd5.PNG)

I don't know how much does it influence the app later.

**Comment by nisevi** [comment]
Hey @bryszard I'm not 100% sure but it may be that you need to configure the API key for Google Geocoding to work.

I just hit this one:
![image](https://user-images.githubusercontent.com/3024789/32634712-38f483d4-c5ad-11e7-9022-f3afe7b44836.png)
and it may be related to what you are experiencing :+1:

**Comment by tansaku** [comment]
@nisevi I think it's a different issue that I would like to fix

Was just talking to HarshDeep about it in #localsupport-install

**Comment by nisevi** [comment]
This is related to the query limit the API key has.

[Here](https://developers.google.com/maps/documentation/javascript/get-api-key) we can get an API key but it would have a limit associated with the [billing plan](https://developers.google.com/maps/pricing-and-plans/) since this is part of the installation it won't affect your local environment, it just will spend some time on it.
